### ISSUE TITLE
palemoon-bin broken

### ISSUE THREAD

**Issue by LinuxLowell** [obrevenge/revenge_repo#1]
Fails CLI and in package manager.  Cut and paste the pacman output below.  Installing from source version does work but it takes hours to compile and install.  I executed this right after a successful 'pacman -Syu'./

[lowell@hades ~]$ sudo pacman -S palemoon-bin
resolving dependencies...
looking for conflicting packages...

Packages (2) mime-types-9-1  palemoon-bin-27.1.0-1

Total Download Size:   33.94 MiB
Total Installed Size:  95.50 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'palemoon-bin-27.1.0-1-x86_64.pkg.tar.xz' from raw.github.com : The requested URL returned error: 404
error: failed retrieving file 'palemoon-bin-27.1.0-1-x86_64.pkg.tar.xz' from downloads.sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'palemoon-bin-27.1.0-1-x86_64.pkg.tar.xz' from ftp.heanet.ie : Server denied you to change to the given directory
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
[lowell@hades ~]$

**Comment by spookykidmm** [comment]
Hey sorry, palemoon(no bin) is the actual palemoon package. Palemoon-bin is a version we no longer actually have in the repos

**Comment by LinuxLowell** [comment]
Thanks for the update. So one question and one comment.

Question.. why would you maintain the source version (it takes hours to compile - a huge inhibitor to use pale moon) and not the bin?  Or is it exactly that, the overhead to maintain it is too much for something not a lot of people use?  I use it because I need something gecko based but doesn't have the Firefox bloat and privacy issues.

Now the comment... do you know the bin is still showing up in your repo manifest?

[lowell@hades ~]$ pacman -Ss palemoon
revenge_repo/arch-palemoon-search 0.1-2
    Pale Moon Arch search engines (AUR, Pkgs, BBS, Wiki, etc.)
revenge_repo/palemoon 27.3.0-1
    Open source web browser based on Firefox focusing on efficiency.
**revenge_repo/palemoon-bin 27.1.0-1**
    Open source web browser based on Firefox focusing on efficiency.
[lowell@hades ~]$

**Comment by LinuxLowell** [comment]
Ok.. just had a "duh" moment. I'd assumed the "palemoon" package in the revenge repo was the same as in aur, a source package.  Just installed palemoon and it is a binary, not a source package. 

If I could make a suggestion.. remove the palemoon-bin from your repo manifest.  When I saw both packages there I assumed it was the same as aur, a binary and source package.  Last time I tried it, the bin package in aur also failed to install (a couple of months ago). As such I didn't even think to try the non "bin" package from revenge until I started thinking about your comment.

**Comment by spookykidmm** [comment]
I honestly don't know how to remove old repo packages from the database, sorry. If you know, please let me know how to

**Comment by LinuxLowell** [comment]
Haven't done package building in a long time and never for arch.  I'm sure the principals are the same.  Did you set the "replaces" variable in the PKGBUILD for palemoon?

**Comment by LinuxLowell** [comment]
> replaces — which package(s) does this package replace? This is appropriate when naming changes between package versions, or when a program is renamed. For example, the Electron framework on which the Atom text editor and Visual Studio Code are built was previously called “Atom Shell”. So it would be appropriate for an Electron PKGBUILD to include atom-shell in its replaces field.

https://fusion809.github.io/how-to-create-archlinux-repository/

**Comment by spookykidmm** [comment]
After some trial and error this morning, I figured it out! Sorry for all the confusion!
